# Generated by Django 3.2.25 on 2025-04-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250407_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingridients',
            new_name='ingridients',
        ),
    ]
